name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build app and create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Java
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: ./packages/poke_list
      - name: Build app
        run: flutter build apk --release
      - name: Create Release
        uses: ncipollo/release-action@v1.11.2
        with:
         artifacts: 'build/app/outputs/flutter-apk/*.apk'
