name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Run Flutter analyze and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
        working-directory: ./packages/poke_list
      - run: flutter analyze
        working-directory: ./packages/poke_list
      - run: flutter test --coverage
        working-directory: ./packages/poke_list
      - run: flutter test --machine > test-results.json
        working-directory: ./packages/poke_list
      - uses: dorny/test-reporter@v1.6.0
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 0